//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public Nullable<int> IdBook { get; set; }
        public string NameBook { get; set; }
        public Nullable<double> PriceBook { get; set; }
        public string ImageBook { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> SallePrice { get; set; }
    }
}
