//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string FirstNameEnglish { get; set; }
        public string LastNameEnglish { get; set; }
        public string FirstNameHebrew { get; set; }
        public string LastNameHebrew { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string NumberHome { get; set; }
        public string NumberPhone1 { get; set; }
        public string NumberPhone2 { get; set; }
        public string selectedTitle { get; set; }
        public string selectedCountry { get; set; }
        public string PostCode { get; set; }
        public string Email { get; set; }
        public string Bio { get; set; }
        public Nullable<bool> Students { get; set; }
        public Nullable<bool> WithoutStudemt { get; set; }
        public Nullable<bool> EAJS { get; set; }
        public Nullable<bool> AJS { get; set; }
        public Nullable<bool> Hebrew { get; set; }
        public Nullable<bool> English { get; set; }
        public Nullable<bool> Both { get; set; }
    }
}
